/*** Autogenerated by WIDL 11.0-rc1 from dlls/windows.perception.stub/async_private.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __async_private_h__
#define __async_private_h__

/* Forward declarations */

#ifndef ____x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_FWD_DEFINED__
#define ____x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_FWD_DEFINED__
typedef interface __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl;
#ifdef __cplusplus
#define __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl ABI::Wine::Internal::IAsyncOperationCompletedHandlerImpl
namespace ABI {
    namespace Wine {
        namespace Internal {
            interface IAsyncOperationCompletedHandlerImpl;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWine_CInternal_CIAsyncInfoImpl_FWD_DEFINED__
#define ____x_ABI_CWine_CInternal_CIAsyncInfoImpl_FWD_DEFINED__
typedef interface __x_ABI_CWine_CInternal_CIAsyncInfoImpl __x_ABI_CWine_CInternal_CIAsyncInfoImpl;
#ifdef __cplusplus
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl ABI::Wine::Internal::IAsyncInfoImpl
namespace ABI {
    namespace Wine {
        namespace Internal {
            interface IAsyncInfoImpl;
        }
    }
}
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <propidl.h>
#include <inspectable.h>
#include <asyncinfo.h>
#include <windowscontracts.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IAsyncOperationCompletedHandlerImpl interface
 */
#ifndef ____x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_INTERFACE_DEFINED__
#define ____x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_INTERFACE_DEFINED__

#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Wine {
        namespace Internal {
            interface IAsyncOperationCompletedHandlerImpl : public IUnknown
            {
                virtual HRESULT STDMETHODCALLTYPE Invoke(
                    IInspectable *async,
                    AsyncStatus status) = 0;

            };
        }
    }
}
extern "C" {
#else
typedef struct __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl *This);

    /*** IAsyncOperationCompletedHandlerImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl *This,
        IInspectable *async,
        AsyncStatus status);

    END_INTERFACE
} __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImplVtbl;

interface __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl {
    CONST_VTBL __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IAsyncOperationCompletedHandlerImpl methods ***/
#define __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_Invoke(This,async,status) (This)->lpVtbl->Invoke(This,async,status)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_QueryInterface(__x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_AddRef(__x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_Release(__x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IAsyncOperationCompletedHandlerImpl methods ***/
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_Invoke(__x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl* This,IInspectable *async,AsyncStatus status) {
    return This->lpVtbl->Invoke(This,async,status);
}
#endif
#ifdef WIDL_using_Wine_Internal
#define IAsyncOperationCompletedHandlerImplVtbl __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImplVtbl
#define IAsyncOperationCompletedHandlerImpl __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl
#define IAsyncOperationCompletedHandlerImpl_QueryInterface __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_QueryInterface
#define IAsyncOperationCompletedHandlerImpl_AddRef __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_AddRef
#define IAsyncOperationCompletedHandlerImpl_Release __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_Release
#define IAsyncOperationCompletedHandlerImpl_Invoke __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_Invoke
#endif /* WIDL_using_Wine_Internal */
#endif

#endif

#endif  /* ____x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncInfoImpl interface
 */
#ifndef ____x_ABI_CWine_CInternal_CIAsyncInfoImpl_INTERFACE_DEFINED__
#define ____x_ABI_CWine_CInternal_CIAsyncInfoImpl_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWine_CInternal_CIAsyncInfoImpl, 0xd81ab70d, 0x82e0, 0x481c, 0x98,0x3d, 0x40,0x12,0x25,0xd9,0x8a,0x2c);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Wine {
        namespace Internal {
            MIDL_INTERFACE("d81ab70d-82e0-481c-983d-401225d98a2c")
            IAsyncInfoImpl : public IUnknown
            {
                virtual HRESULT STDMETHODCALLTYPE put_Completed(
                    ABI::Wine::Internal::IAsyncOperationCompletedHandlerImpl *handler) = 0;

                virtual HRESULT STDMETHODCALLTYPE get_Completed(
                    ABI::Wine::Internal::IAsyncOperationCompletedHandlerImpl **handler) = 0;

                virtual HRESULT STDMETHODCALLTYPE get_Result(
                    PROPVARIANT *result) = 0;

                virtual HRESULT STDMETHODCALLTYPE Start(
                    ) = 0;

            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWine_CInternal_CIAsyncInfoImpl, 0xd81ab70d, 0x82e0, 0x481c, 0x98,0x3d, 0x40,0x12,0x25,0xd9,0x8a,0x2c)
#endif
#else
typedef struct __x_ABI_CWine_CInternal_CIAsyncInfoImplVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This);

    /*** IAsyncInfoImpl methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Completed)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This,
        __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl *handler);

    HRESULT (STDMETHODCALLTYPE *get_Completed)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This,
        __x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl **handler);

    HRESULT (STDMETHODCALLTYPE *get_Result)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This,
        PROPVARIANT *result);

    HRESULT (STDMETHODCALLTYPE *Start)(
        __x_ABI_CWine_CInternal_CIAsyncInfoImpl *This);

    END_INTERFACE
} __x_ABI_CWine_CInternal_CIAsyncInfoImplVtbl;

interface __x_ABI_CWine_CInternal_CIAsyncInfoImpl {
    CONST_VTBL __x_ABI_CWine_CInternal_CIAsyncInfoImplVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_Release(This) (This)->lpVtbl->Release(This)
/*** IAsyncInfoImpl methods ***/
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_put_Completed(This,handler) (This)->lpVtbl->put_Completed(This,handler)
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_get_Completed(This,handler) (This)->lpVtbl->get_Completed(This,handler)
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_get_Result(This,result) (This)->lpVtbl->get_Result(This,result)
#define __x_ABI_CWine_CInternal_CIAsyncInfoImpl_Start(This) (This)->lpVtbl->Start(This)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncInfoImpl_QueryInterface(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWine_CInternal_CIAsyncInfoImpl_AddRef(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWine_CInternal_CIAsyncInfoImpl_Release(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This) {
    return This->lpVtbl->Release(This);
}
/*** IAsyncInfoImpl methods ***/
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncInfoImpl_put_Completed(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This,__x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl *handler) {
    return This->lpVtbl->put_Completed(This,handler);
}
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncInfoImpl_get_Completed(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This,__x_ABI_CWine_CInternal_CIAsyncOperationCompletedHandlerImpl **handler) {
    return This->lpVtbl->get_Completed(This,handler);
}
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncInfoImpl_get_Result(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This,PROPVARIANT *result) {
    return This->lpVtbl->get_Result(This,result);
}
static inline HRESULT __x_ABI_CWine_CInternal_CIAsyncInfoImpl_Start(__x_ABI_CWine_CInternal_CIAsyncInfoImpl* This) {
    return This->lpVtbl->Start(This);
}
#endif
#ifdef WIDL_using_Wine_Internal
#define IID_IAsyncInfoImpl IID___x_ABI_CWine_CInternal_CIAsyncInfoImpl
#define IAsyncInfoImplVtbl __x_ABI_CWine_CInternal_CIAsyncInfoImplVtbl
#define IAsyncInfoImpl __x_ABI_CWine_CInternal_CIAsyncInfoImpl
#define IAsyncInfoImpl_QueryInterface __x_ABI_CWine_CInternal_CIAsyncInfoImpl_QueryInterface
#define IAsyncInfoImpl_AddRef __x_ABI_CWine_CInternal_CIAsyncInfoImpl_AddRef
#define IAsyncInfoImpl_Release __x_ABI_CWine_CInternal_CIAsyncInfoImpl_Release
#define IAsyncInfoImpl_put_Completed __x_ABI_CWine_CInternal_CIAsyncInfoImpl_put_Completed
#define IAsyncInfoImpl_get_Completed __x_ABI_CWine_CInternal_CIAsyncInfoImpl_get_Completed
#define IAsyncInfoImpl_get_Result __x_ABI_CWine_CInternal_CIAsyncInfoImpl_get_Result
#define IAsyncInfoImpl_Start __x_ABI_CWine_CInternal_CIAsyncInfoImpl_Start
#endif /* WIDL_using_Wine_Internal */
#endif

#endif

#endif  /* ____x_ABI_CWine_CInternal_CIAsyncInfoImpl_INTERFACE_DEFINED__ */

typedef HRESULT (*async_operation_callback)(IUnknown *invoker,IUnknown *param,PROPVARIANT *result,BOOL called_async);
/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
ULONG           __RPC_USER LPSAFEARRAY_UserSize     (ULONG *, ULONG, LPSAFEARRAY *);
unsigned char * __RPC_USER LPSAFEARRAY_UserMarshal  (ULONG *, unsigned char *, LPSAFEARRAY *);
unsigned char * __RPC_USER LPSAFEARRAY_UserUnmarshal(ULONG *, unsigned char *, LPSAFEARRAY *);
void            __RPC_USER LPSAFEARRAY_UserFree     (ULONG *, LPSAFEARRAY *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __async_private_h__ */
